// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using SkeletonView.Extensions;

namespace SkeletonView.Exemple
{
    public partial class Cell : UITableViewCell
    {
        public Cell(IntPtr handle) : base(handle)
        {
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();

            avatarImage.SetIsSkeletonable(true);
            label1.SetIsSkeletonable(true);
        }
    }
}
